// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Web_Vue.Server.Models;

#nullable disable

namespace Web_Vue.Server.Models.Migrations
{
    [DbContext(typeof(DbEntityContext))]
    partial class DbEntityContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Web_Vue.Server.Models.Entities.Permission", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasComment("主鍵");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasComment("權限代碼");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("建立時間");

                    b.Property<string>("CreateUser")
                        .HasColumnType("text")
                        .HasComment("建立人員");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("boolean")
                        .HasComment("是否已刪除");

                    b.Property<bool>("IsDisplay")
                        .HasColumnType("boolean")
                        .HasComment("是否顯示於權限清單上");

                    b.Property<bool>("IsEnable")
                        .HasColumnType("boolean")
                        .HasComment("是否啟用");

                    b.Property<bool>("IsFolder")
                        .HasColumnType("boolean")
                        .HasComment("是否為資料夾節點");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasComment("權限名稱");

                    b.Property<int?>("ParentID")
                        .HasColumnType("integer")
                        .HasComment("父節點");

                    b.Property<int>("Sort")
                        .HasColumnType("integer")
                        .HasComment("排序");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("更新時間");

                    b.Property<string>("UpdateUser")
                        .HasColumnType("text")
                        .HasComment("更新人員");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasComment("路徑");

                    b.HasKey("ID");

                    b.ToTable("Permission", t =>
                        {
                            t.HasComment("權限資料表");
                        });
                });

            modelBuilder.Entity("Web_Vue.Server.Models.Entities.PermissionInRole", b =>
                {
                    b.Property<int>("RoleID")
                        .HasColumnType("integer")
                        .HasComment("角色ID");

                    b.Property<int>("PermissionID")
                        .HasColumnType("integer")
                        .HasComment("權限ID");

                    b.HasKey("RoleID", "PermissionID");

                    b.ToTable("PermissionInRole", t =>
                        {
                            t.HasComment("權限角色關聯表(多對多)");
                        });
                });

            modelBuilder.Entity("Web_Vue.Server.Models.Entities.Role", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasComment("主鍵");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasComment("角色代碼");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("建立時間");

                    b.Property<string>("CreateUser")
                        .HasColumnType("text")
                        .HasComment("建立人員");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasComment("備註");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean")
                        .HasComment("是否為系統管理者");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("boolean")
                        .HasComment("是否已刪除");

                    b.Property<bool>("IsEnable")
                        .HasColumnType("boolean")
                        .HasComment("啟用狀態");

                    b.Property<bool>("IsMaintaining")
                        .HasColumnType("boolean")
                        .HasComment("是否系統維護中");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasComment("角色名稱");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("更新時間");

                    b.Property<string>("UpdateUser")
                        .HasColumnType("text")
                        .HasComment("更新人員");

                    b.HasKey("ID");

                    b.ToTable("Role", t =>
                        {
                            t.HasComment("角色資料表");
                        });
                });

            modelBuilder.Entity("Web_Vue.Server.Models.Entities.RoleInUserAccount", b =>
                {
                    b.Property<int>("UserAccountID")
                        .HasColumnType("integer")
                        .HasComment("使用者ID");

                    b.Property<int>("RoleID")
                        .HasColumnType("integer")
                        .HasComment("角色ID");

                    b.HasKey("UserAccountID", "RoleID");

                    b.ToTable("RoleInUserAccount", t =>
                        {
                            t.HasComment("角色使用者關聯表(多對多)");
                        });
                });

            modelBuilder.Entity("Web_Vue.Server.Models.Entities.UserAccount", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasComment("主鍵");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("Account")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)")
                        .HasComment("帳號");

                    b.Property<bool>("IsTemplatePassword")
                        .HasColumnType("boolean")
                        .HasComment("為暫時密碼");

                    b.Property<DateTime?>("LatestLoginDate")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("最後登入日期");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("character varying(255)")
                        .HasComment("密碼");

                    b.Property<DateTime?>("ValidPasswordExpireTime")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("驗證密碼有效期限");

                    b.HasKey("ID");

                    b.ToTable("UserAccount", t =>
                        {
                            t.HasComment("使用者帳號");
                        });
                });

            modelBuilder.Entity("Web_Vue.Server.Models.Entities.UserProfile", b =>
                {
                    b.Property<int>("ID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("建立時間");

                    b.Property<string>("CreateUser")
                        .HasColumnType("text")
                        .HasComment("建立人員");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("boolean")
                        .HasComment("是否已刪除");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("姓名");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasComment("是否啟用 (1:啟用, 2:停用)");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("更新時間");

                    b.Property<string>("UpdateUser")
                        .HasColumnType("text")
                        .HasComment("更新人員");

                    b.HasKey("ID");

                    b.ToTable("UserProfile", t =>
                        {
                            t.HasComment("使用者資訊資料表");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
